lib/leodi_dashboard_web/router.ex
defmodule LeodiDashboardWeb.Router do
  use LeodiDashboardWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowPersistentSession]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session do
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, "session.html"}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser
    pipe_through :session

    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", LeodiDashboardWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    get "/recipes", RecipeController, :index
    # get "/recipes/new", RecipeController, :new
    live "/recipes/new", RecipeLive.New, :new
    get "/recipes/:id", RecipeController, :show
    delete "/recipes/:id", RecipeController, :delete

    live "/recipes/:id/edit", RecipeLive.Edit, :edit

    get "/recipe_lists", RecipeListController, :index
    live "/recipe_lists/new", RecipeListLive.New, :new
    live "/recipe_lists/:id/edit", RecipeListLive.Edit, :edit
    get "/recipe_lists/:id", RecipeListController, :show
    delete "/recipe_list/:id", RecipeListController, :delete

    resources "/ingredients", IngredientController
    resources "/recipe-ingredients", RecipeIngredientController, only: [:delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", LeodiDashboardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LeodiDashboardWeb.Telemetry
    end
  end
end

lib/leodi_dashboard_web/controllers/recipe_list_controller.ex
defmodule LeodiDashboardWeb.RecipeListController do
  use LeodiDashboardWeb, :controller

  alias LeodiDashboard.List
  alias LeodiDashboard.Lists.RecipeList

  def index(conn, _params) do
    recipe_lists = List.list_recipe_lists()
    render(conn, "index.html", recipe_lists: recipe_lists)
  end

  def show(conn, %{"id" => id}) do
    recipe_list = List.get_recipe_list!(id)

    render(
      conn,
      "show.html",
      recipe_list: recipe_list
    )
  end

  def delete(conn, %{"id" => id}) do
    recipe_list = List.get_recipe_list!(id)
    {:ok, _recipe_list} = List.delete_recipe_list(recipe_list)

    conn
    |> put_flash(:info, "RecipeList deleted successfully.")
    |> redirect(to: Routes.recipe_list_path(conn, :index))
  end
end

lib/leodi_dashboard_web/views/recipe_list_view.ex
defmodule LeodiDashboardWeb.RecipeListView do
  use LeodiDashboardWeb, :view

  def is_active?(true), do: "is-active"
  def is_active?(_), do: ""
end

lib/leodi_dashboard_web/templates/recipe_list/edit.html.leex
<div class="container p-4">
  <h1 class="title"><%= @recipe_list.name %></h1>
  <div class="columns">
    <div class="column">
      <div class="card">
        <div class="card-header">
          <h2 class="card-header-title subtitle">Info</h2>
        </div>
        <div class="card-content">
          <form action="#" phx-submit="update_recipe">
            <div class="field">
              <div class="control">
                <%= label :recipe_list, :name, class: "label" %>
                <%= text_input :recipe_list, :name, class: "input", value: @recipe_list.name %>
              </div>
            </div>

            <%= hidden_input :recipe, :id, value: @recipe_list.id %>
            <div class="field">
              <%= submit "Save", class: "button is-primary", phx_disable_with: "Saving.." %>
            </div>
          </form>
        </div>
        <div class="card">
          <div class="card-header">
            <h2 class="card-header-title">
              Recipes
            </h2>
          </div>
          <div class="card-content">
            <table class="table" style="width: 100%">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <%= for recipe_list_recipe <- @recipe_list_recipes do %>
                  <tr>
                    <td>
                      <%= recipe_list_recipe.recipe.name %>
                    </td>
                    <td>
                      <form action="#" phx-submit="delete_recipe_list_recipe">
                        <%= hidden_input :recipe_list, :id, value: @recipe_list.id %>
                        <%= hidden_input :recipe_list_recipe, :id, value: recipe_list_recipe.id %>
                        <%= submit "Del", phx_disable_with: "Deleting..", class: "button is-danger" %>
                      </form>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="card">
        <div class="card-header">
          <h2 class="card-header-title subtitle level-item">Recipes</h2>
        </div>
        <div class="card-content">
          <div class="level">
            <div class="level-left">
              <button class="button is-link level-item" phx-click="toggle-modal">Add Recipes</button>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="modal <%= is_active?(@modal_open) %>">
      <div class="modal-background">
      </div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Add Recipes</p>
          <button class="delete" aria-label="close"  phx-click="toggle-modal"></button>
        </header>
        <section class="modal-card-body">
          <form action="#" phx-change="search-recipes" phx-debounce="2000" class="mb-5">
            <div class="field">
              <div class="control">
                <input type="text" name="search-recipes" class="input" placeholder="Search ingredients.." />
              </div>
            </div>
          </form>
          <ul>
            <%= for recipe <- @recipes do %>
              <li>
                <form action="#" phx-submit="add_recipe" class="form">
                  <div class="columns">
                    <div class="column">
                      <h3><%= recipe.name %></h3>
                    </div>
                    <div class="column">
                    </div>
                    <div class="column">
                      <%= hidden_input :recipe, :id, value: recipe.id %>
                      <%= hidden_input :recipe_list, :id, value: @recipe_list.id %>
                      <%= submit "Add", phx_disable_with: "Adding..", class: "button is-primary" %>
                    </div>
                  </div>
                </form>
              </li>
            <% end %>
          </ul>
        </section>
      </div>
    </div>
  </div>

lib/leodi_dashboard_web/templates/recipe_list/index.html.eex
<div class="container p-4">
  <div class="level">
    <div class="level-left">
      <h1 class="title level-item">Recipe Lists</h1>
    </div>
    <div class="level-right">
      <%= link "New Recipe List", to: Routes.recipe_list_new_path(@conn, :new), class: "button is-link level-item" %>
    </div>
  </div>

  <div class="columns">
    <div class="column recipe-list">
      <%= for recipe_list <- @recipe_lists do %>
        <div class="card mb-2 recipe-list-item">
          <header class="card-header">
            <h2 class="card-header-title subtitle">
              <%= recipe_list.name %>
            </h2>
          </header>
          <div class="card-content">
            <div class="content">
            </div>
          </div>
          <footer class="card-footer">
            <%= link "Show", to: Routes.recipe_list_path(@conn, :show, recipe_list), class: "card-footer-item" %>
            <%= link "Edit", to: Routes.recipe_list_edit_path(@conn, :edit, recipe_list), class: "card-footer-item" %>
            <%= link "Delete", to: Routes.recipe_list_path(@conn, :delete, recipe_list), method: :delete, data: [confirm: "Are you sure?"], class: "card-footer-item" %>
          </footer>
        </div>
      <% end %>
    </div>
  </div>
</div>

lib/leodi_dashboard_web/templates/recipe_list/new.html.leex
<div class="container p-4">
  <div class="level">
    <div class="level-left">
      <h1 class="title level-item">New RecipeList</h1>
    </div>
  </div>

  <div class="columns">
    <div class="column is-three-quarter-desktop">
      <div class="card">
        <div class="card-content">
          <%= f = form_for @changeset, "#", [phx_submit: :create] %>
            <div class="field">
              <div class="control">
                <%= label f, :name, class: "label" %>
                <%= text_input f, :name, class: "input" %>
                <%= error_tag f, :name %>
              </div>
            </div>

            <div class="field">
              <%= submit "Save", class: "button is-primary", phx_disable_with: "Saving.." %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>