lib/leodi_dashboard_web/router.ex
defmodule LeodiDashboardWeb.Router do
  use LeodiDashboardWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowPersistentSession]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session do
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, "session.html"}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser
    pipe_through :session

    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", LeodiDashboardWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    get "/recipes", RecipeController, :index
    # get "/recipes/new", RecipeController, :new
    live "/recipes/new", RecipeLive.New, :new
    get "/recipes/:id", RecipeController, :show
    delete "/recipes/:id", RecipeController, :delete

    live "/recipes/:id/edit", RecipeLive.Edit, :edit

    get "/recipe_lists", RecipeListController, :index
    live "/recipe_lists/new", RecipeListLive.New, :new
    live "/recipe_lists/:id/edit", RecipeListLive.Edit, :edit
    get "/recipe_lists/:id", RecipeListController, :show
    delete "/recipe_list/:id", RecipeListController, :delete

    resources "/ingredients", IngredientController
    resources "/recipe-ingredients", RecipeIngredientController, only: [:delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", LeodiDashboardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LeodiDashboardWeb.Telemetry
    end
  end
end

lib/leodi_dashboard/lists/recipe.ex
defmodule LeodiDashboard.List.RecipeList do
  use Ecto.Schema

  import Ecto.Changeset
  import Ecto.Query, warn: false

  alias LeodiDashboard.Repo
  alias LeodiDashboard.Meal.Recipe

  schema "recipe_lists" do
    many_to_many(
      :recipes,
      Recipe,
      join_through: "recipe_list_recipes",
      on_delete: :delete_all
    )

    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(recipe, attrs) do
    recipe
    |> cast(attrs, [:name])
    |> validate_required([:name])
    |> unique_constraint(:name)
    |> foreign_key_constraint(:recipe_lists_recipe_id_fkey)
  end
end

lib/leodi_dashboard/meal/recipe.ex
defmodule LeodiDashboard.Meal.Recipe do
  use Ecto.Schema

  import Ecto.Changeset
  import Ecto.Query, warn: false

  alias LeodiDashboard.Repo

  alias LeodiDashboard.Meal.RecipeIngredient
  alias LeodiDashboard.Meal.Ingredient

  schema "recipes" do
    many_to_many(
      :ingredients,
      Ingredient,
      join_through: RecipeIngredient,
      on_replace: :delete
    )

    field :description, :string
    field :name, :string
    field :url, :string

    timestamps()
  end

  @doc false
  def changeset(recipe, attrs) do
    recipe
    |> cast(attrs, [:name, :url, :description])
    |> validate_required([:name, :url, :description])
    |> foreign_key_constraint(:recipe_ingredients_recipe_id_fkey)
    |> unique_constraint(:name)
  end
end

lib/leodi_dashboard_web/controllers/recipe_controller.ex
defmodule LeodiDashboardWeb.RecipeController do
  use LeodiDashboardWeb, :controller

  alias LeodiDashboard.Meal
  alias LeodiDashboard.Meal.Recipe

  def index(conn, _params) do
    recipes = Meal.list_recipes()
    render(conn, "index.html", recipes: recipes)
  end

  def new(conn, _params) do
    changeset = Meal.change_recipe(%Recipe{})
    ingredients = Meal.list_ingredients()

    render(conn, "new.html", changeset: changeset, ingredients: ingredients)
  end

  def create(conn, %{"recipe" => recipe_params}) do
    case Meal.create_recipe(filter_ingredients(recipe_params)) do
      {:ok, recipe} ->
        conn
        |> put_flash(:info, "Recipe created successfully.")
        |> redirect(to: Routes.recipe_path(conn, :show, recipe), ingredients: [])

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, ingredients: [])
    end
  end

  def show(conn, %{"id" => id}) do
    recipe = Meal.get_recipe!(id)
    recipe_ingredients = Meal.get_recipe_ingredients!(recipe)

    render(
      conn,
      "show.html",
      recipe: recipe,
      recipe_ingredients: recipe_ingredients
    )
  end

  def edit(conn, %{"id" => id}) do
    recipe = Meal.get_recipe!(id)
    changeset = Meal.change_recipe(recipe)
    ingredients = Meal.list_ingredients()

    render(conn, "edit.html", recipe: recipe, changeset: changeset, ingredients: ingredients)
  end

  def update(conn, %{"id" => id, "recipe" => recipe_params}) do
    recipe = Meal.get_recipe!(id)

    case Meal.update_recipe_with_ingredients(recipe, filter_ingredients(recipe_params)) do
      {:ok, %{recipe: recipe}} ->
        conn
        |> put_flash(:info, "Recipe updated successfully.")
        |> redirect(to: Routes.recipe_path(conn, :show, recipe))

      {:error, %Ecto.Changeset{} = changeset} ->
        ingredients = Meal.list_ingredients()
        render(conn, "edit.html", recipe: recipe, changeset: changeset, ingredients: ingredients)
    end
  end

  def delete(conn, %{"id" => id}) do
    recipe = Meal.get_recipe!(id)
    {:ok, _recipe} = Meal.delete_recipe(recipe)

    conn
    |> put_flash(:info, "Recipe deleted successfully.")
    |> redirect(to: Routes.recipe_path(conn, :index))
  end

  defp filter_ingredients(%{"ingredients" => ingredients} = params) when is_map(ingredients) do
    updated_ingredients =
      ingredients
      |> Enum.filter(fn {key, values} ->
        if values["picked"] do
          true
        else
          false
        end
      end)

    params |> Map.put("ingredients", updated_ingredients)
  end

  defp filter_ingredients(params), do: params
end

lib/leodi_dashboard_web/live/recipe_live.ex
defmodule LeodiDashboardWeb.RecipeLive.Edit do
  use LeodiDashboardWeb, :live_view
  alias LeodiDashboard.Meal

  def render(assigns) do
   Phoenix.View.render(LeodiDashboardWeb.RecipeView, "edit.html", assigns)
  end

  def mount(%{"id" => recipe_id} = params, session, socket) do
    recipe = Meal.get_recipe!(recipe_id)
    recipe_ingredients = Meal.get_recipe_ingredients!(recipe)
    ingredients =
      Meal.list_ingredients()
      |> filter_recipe_ingredients(recipe_ingredients)

    {
      :ok,
      socket
      |> assign(:recipe, recipe)
      |> assign(:recipe_ingredients, recipe_ingredients)
      |> assign(:ingredients, ingredients)
    }
  end

  def handle_event("update_recipe", %{"recipe" => %{"id" => recipe_id} = params}, socket) do
    recipe = Meal.get_recipe!(recipe_id)

    Meal.update_recipe(recipe, params)

    {:noreply, fetch(socket, recipe.id)}
  end

  def handle_event(
    "add_recipe_ingredient",
    %{
      "recipe" => %{
        "id" => recipe_id,
        "ingredient_id" => ingredient_id
      },
      "recipe_ingredient" => attrs
    } = params,
    socket
  ) do
    recipe = Meal.get_recipe!(recipe_id)
    ingredient = Meal.get_ingredient!(ingredient_id)

    Meal.create_recipe_ingredient(recipe, ingredient, attrs)

    {:noreply, fetch(socket, recipe.id) |> put_flash(:info, "Ingredient added")}
  end

  def handle_event(
    "delete_recipe_ingredient",
    %{
      "recipe" => %{
        "id" => recipe_id,
        "recipe_ingredient_id" => recipe_ingredient_id
      }
    } = _params,
    socket
  ) do
    ingredient = Meal.get_recipe_ingredient!(recipe_ingredient_id)
    {:ok, _ingredient} = Meal.delete_recipe_ingredient(ingredient)

    {
      :noreply,
      fetch(socket, recipe_id)
    }
  end

  defp filter_recipe_ingredients(ingredients, recipe_ingredients) do
    Enum.filter(ingredients, fn ingredient ->
      case Enum.find(recipe_ingredients, fn r_i ->
        ingredient.id == r_i.ingredient.id
      end) do
        nil -> true
        _ -> false
      end
    end)
  end

  defp fetch(socket, recipe_id) do
    recipe = Meal.get_recipe!(recipe_id)
    recipe_ingredients = Meal.get_recipe_ingredients!(recipe)
    ingredients =
      Meal.list_ingredients()
      |> filter_recipe_ingredients(recipe_ingredients)

    socket
    |> assign(:recipe, Meal.get_recipe!(recipe_id))
    |> assign(:recipe_ingredients, recipe_ingredients)
    |> assign(:ingredients, ingredients)
  end
end

lib/leodi_dashboard_web/views/recipe_view.ex
defmodule LeodiDashboardWeb.RecipeView do
  use LeodiDashboardWeb, :view

  def is_active?(true), do: "is-active"
  def is_active?(_), do: ""

  def link_recipe_ingredients(ingredients, recipe_ingredients) do
    Enum.map(recipe_ingredients, fn r_i ->
      i = ingredients |> Enum.find(&(&1.id == r_i.ingredient_id))

      r_i
      |> Map.merge(Map.take(i, [:name]))
    end)
  end

  def multiselect_ingredients(form, field, options, opts \\ []) do
    {selected, _} = get_selected_values(form, field, opts)
    selected_as_strings = Enum.map(selected, &"#{&1}")

    for {value, key} <- options, into: [] do
      checkbox =
        content_tag(:label, class: "label") do
          [
            tag(:input,
              name: input_name(form, field) <> "[]",
              id: input_id(form, field, key),
              type: "checkbox",
              value: key,
              checked: Enum.member?(selected_as_strings, "#{key}")
            ),
            value
          ]
        end

      amount =
        content_tag(:label, class: "label") do
          [
            tag(:input,
              name: "recipe[ingredients][#{key}][amount]",
              id: "recipe_ingredients_amount"
            )
          ]
        end

      picked =
        tag(:input,
          name: "recipe[ingredients][#{key}][picked]",
          type: "checkbox",
          id: "recipe_ingredients_picked"
        )

      [value, picked, amount]
    end
  end

  defp get_selected_values(form, field, opts) do
    {selected, opts} = Keyword.pop(opts, :selected)
    param = field_to_string(field)

    case form do
      %{params: %{^param => sent}} ->
        {sent, opts}

      _ ->
        {selected || input_value(form, field), opts}
    end
  end

  defp field_to_string(field) when is_atom(field), do: Atom.to_string(field)
  defp field_to_string(field) when is_binary(field), do: field
end

lib/leodi_dashboard_web/templates/recipe/edit.html.leex
<div class="container p-4">
  <h1 class="title"><%= @recipe.name %></h1>
  <div class="columns">
    <div class="column">
      <div class="card">
        <div class="card-header">
          <h2 class="card-header-title subtitle">Info</h2>
        </div>
        <div class="card-content">
          <form action="#" phx-submit="update_recipe">
            <div class="field">
              <div class="control">
                <%= label :recipe, :name, class: "label" %>
                <%= text_input :recipe, :name, class: "input", value: @recipe.name %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= label :recipe, :url, class: "label" %>
                <%= text_input :recipe, :url, class: "input", value: @recipe.url %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= label :recipe, :description, class: "label" %>
                <%= textarea :recipe, :description, class: "input", value: @recipe.description %>
              </div>
            </div>

            <%= hidden_input :recipe, :id, value: @recipe.id %>
            <div class="field">
              <%= submit "Save", class: "button is-primary", phx_disable_with: "Saving.." %>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="card">
        <div class="card-header">
          <h2 class="card-header-title subtitle level-item">Ingredients</h2>
        </div>
        <div class="card-content">
          <div class="level">
            <div class="level-left">
              <button class="button is-link level-item" phx-click="toggle-modal">Add ingredients</button>
            </div>
          </div>
          <table class="table" style="width: 100%">
            <thead>
              <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Unit</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <%= for recipe_ingredient <- @recipe_ingredients do %>
                <tr>
                  <td><%= recipe_ingredient.ingredient.name %></td>
                  <td><%= recipe_ingredient.amount %></td>
                  <td><%= recipe_ingredient.unit %></td>
                  <td>
                    <form action="#" phx-submit="delete_recipe_ingredient">
                      <%= hidden_input :recipe, :id, value: @recipe.id %>
                      <%= hidden_input :recipe, :recipe_ingredient_id, value: recipe_ingredient.id %>
                      <%= submit "Del", phx_disable_with: "Deleting..", class: "button is-danger" %>
                    </form>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="modal <%= is_active?(@modal_open) %>">
      <div class="modal-background">
      </div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Add Ingredients</p>
          <button class="delete js-close-add-ingredients-modal" aria-label="close"  phx-click="toggle-modal"></button>
        </header>
        <section class="modal-card-body">
          <form action="#" phx-change="search-ingredients" phx-debounce="2000" class="mb-5">
            <div class="field">
              <div class="control">
                <input type="text" name="search-ingredients" class="input" placeholder="Search ingredients.." />
              </div>
            </div>
          </form>
          <ul>
            <%= for ingredient <- @ingredients do %>
              <li>
                <form action="#" phx-submit="add_recipe_ingredient" class="form">
                  <div class="columns">
                    <div class="column">
                      <h3><%= ingredient.name %></h3>
                    </div>
                    <div class="column">
                      <%= hidden_input :recipe, :id, value: @recipe.id %>
                      <%= hidden_input :recipe, :ingredient_id, value: ingredient.id %>
                      <div class="field">
                        <div class="control">
                          <%= text_input :recipe_ingredient, :amount, value: "", placeholder: "1..", class: "input" %>
                        </div>
                      </div>
                    </div>
                    <div class="column">
                      <div class="field">
                        <div class="select">
                          <%= select :recipe_ingredient, :unit, [:gram, :mil, :units, :tablespoon, :teaspoon] %>
                        </div>
                      </div>
                    </div>
                    <div class="column">
                      <%= submit "Add", phx_disable_with: "Adding..", class: "button is-primary" %>
                    </div>
                  </div>
                </form>
              </li>
            <% end %>
          </ul>
        </section>
      </div>
    </div>
  </div>

lib/leodi_dashboard_web/templates/recipe/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="columns container">
    <div class="column is-three-quarters">
      <%= if @changeset.action do %>
        <div class="alert alert-danger">
          <p>Oops, something went wrong! Please check the errors below.</p>
        </div>
      <% end %>

      <div class="field">
        <div class="control">
          <%= label f, :name, class: "label" %>
          <%= text_input f, :name, class: "input" %>
        </div>
        <%= error_tag f, :name %>
      </div>

      <div class="field">
        <div class="control">
          <%= label f, :url, class: "label" %>
          <%= text_input f, :url, class: "input" %>
        </div>
        <%= error_tag f, :url %>
      </div>

      <div class="field">
        <div class="control">
          <%= label f, :description, class: "label" %>
          <%= text_input f, :description, class: "input" %>
        </div>
        <%= error_tag f, :description %>
      </div>
    </div>

    <div class="column panel">
      <%= if assigns[:recipe] do %>
        <h2>Ingredienten</h2>
        <%=
          multiselect_ingredients(f,
            :ingredients,
            Enum.map(@ingredients, fn i -> {i.name, i.id} end),
            selected: Enum.map(@recipe.ingredients, &(&1.id))
          )
        %>
        <% end %>
  </div>

  <div class="field">
    <%= submit "Save", class: "button" %>
  </div>
<% end %>

lib/leodi_dashboard_web/templates/recipe/index.html.eex
<div class="container recipe-index p-4">
  <div class="level">
    <div class="level-left">
      <h1 class="title level-item">Listing Recipes</h1>
    </div>
    <div class="level-right">
      <%= link "New Recipe", to: Routes.recipe_new_path(@conn, :new), class: "button is-link level-item" %>
    </div>
  </div>

  <div class="columns">
    <div class="column recipe-list">
      <%= for recipe <- @recipes do %>
        <div class="card mb-2 recipe-list-item">
          <header class="card-header">
            <h2 class="card-header-title subtitle">
              <%= recipe.name %>
            </h2>
          </header>
          <div class="card-content">
            <div class="content">
              <p class="recipe-description">
              <%= recipe.description |> String.slice(0..200) %>...
              </p>
            </div>
          </div>
          <footer class="card-footer">
            <%= link "Show", to: Routes.recipe_path(@conn, :show, recipe), class: "card-footer-item" %>
            <%= link "Edit", to: Routes.recipe_edit_path(@conn, :edit, recipe), class: "card-footer-item" %>
            <%= link "Delete", to: Routes.recipe_path(@conn, :delete, recipe), method: :delete, data: [confirm: "Are you sure?"], class: "card-footer-item" %>
          </footer>
        </div>
      <% end %>
    </div>
  </div>
</div>

lib/leodi_dashboard_web/templates/recipe/new.html.leex
<div class="container p-4">
  <div class="level">
    <div class="level-left">
      <h1 class="title level-item">New Recipe</h1>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <div class="card">
        <div class="card-content">
          <%= f = form_for @changeset, "#", [phx_submit: :create] %>
            <div class="field">
              <div class="control">
                <%= label f, :name, class: "label" %>
                <%= text_input f, :name, class: "input" %>
                <%= error_tag f, :name %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= label f, :url, class: "label" %>
                <%= text_input f, :url, class: "input" %>
                <%= error_tag f, :url %>
              </div>
            </div>

            <div class="field">
              <div class="control">
                <%= label f, :description, class: "label" %>
                <%= textarea f, :description, class: "input" %>
                <%= error_tag f, :description %>
              </div>
            </div>

            <div class="field">
              <%= submit "Save", class: "button", phx_disable_with: "Saving.." %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</div>

lib/leodi_dashboard_web/templates/recipe/show.html.eex
<div class="container recipe-index p-4">
  <h1 class="title"><%= @recipe.name %></h1>
  <div class="columns">
    <div class="column">
      <div class="card mb-2">
        <header class="card-header">
          <h2 class="card-header-title subtitle">
            Info
          </h2>
        </header>
        <div class="card-content">
          <p class="mb-1">
            <%= @recipe.description %>
          </p>
          <p>
            <a href="<%= @recipe.url %>">
              <%= @recipe.url %>
            </a>
          </p>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="card">
        <div class="card-header">
          <h2 class="card-header-title subtitle">
            Ingredients
          </h2>
        </div>
        <div class="card-content">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Unit</th>
              </tr>
            </thead>
            <% ingredients = link_recipe_ingredients(@recipe.ingredients, @recipe_ingredients) %>
            <tbody>
              <%= for ingredient <- ingredients do %>
                <tr>
                  <td><%= ingredient.name %></td>
                  <td><%= ingredient.amount %></td>
                  <td><%= ingredient.unit %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>