lib/leodi_dashboard_web/router.ex
defmodule LeodiDashboardWeb.Router do
  use LeodiDashboardWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowPersistentSession]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session do
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, "session.html"}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser
    pipe_through :session

    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", LeodiDashboardWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    get "/recipes", RecipeController, :index
    # get "/recipes/new", RecipeController, :new
    live "/recipes/new", RecipeLive.New, :new
    get "/recipes/:id", RecipeController, :show
    delete "/recipes/:id", RecipeController, :delete

    live "/recipes/:id/edit", RecipeLive.Edit, :edit

    get "/recipe_lists", RecipeListController, :index
    live "/recipe_lists/new", RecipeListLive.New, :new
    live "/recipe_lists/:id/edit", RecipeListLive.Edit, :edit
    get "/recipe_lists/:id", RecipeListController, :show
    delete "/recipe_list/:id", RecipeListController, :delete

    resources "/ingredients", IngredientController
    resources "/recipe-ingredients", RecipeIngredientController, only: [:delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", LeodiDashboardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LeodiDashboardWeb.Telemetry
    end
  end
end

lib/leodi_dashboard_web/views/layout_view.ex
defmodule LeodiDashboardWeb.LayoutView do
  use LeodiDashboardWeb, :view
end

lib/leodi_dashboard_web/templates/layout/app.html.eex
<main role="main" class="">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <div class="wrapper pt-5 pb-5">
    <%= @inner_content %>
  </div>
</main>

lib/leodi_dashboard_web/templates/layout/live.html.leex
<main role="main" class="">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <div class="wrapper pt-5 pb-5">
    <%= @inner_content %>
  </div>
</main>

lib/leodi_dashboard_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "LeoDi" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section>
        <nav role="navigation" class="navbar" aria-label="main navigation">
          <div class="navbar-brand">
            <%= link to: Routes.page_path(@conn, :index), class: "navbar-item" do %>
              <div class="brand-wrapper">
                <img src="<%= Routes.static_path(@conn, "/images/motto.png") %>" alt="Motto" />
              </div>
            <% end %>
            <a class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
          <div id="navbar-menu" class="navbar-menu">
            <div class="navbar-start">
              <%= link "Recipes", to: Routes.recipe_path(@conn, :index), class: "navbar-item" %>
              <%= link "Ingredients", to: Routes.ingredient_path(@conn, :index), class: "navbar-item" %>
              <%= link "RecipeLists", to: Routes.recipe_list_path(@conn, :index), class: "navbar-item" %>
              <%= if Pow.Plug.current_user(@conn) do %>
                <%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "navbar-item" %></span>
              <% end %>
            </div>
            <div class="navbar-end">
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "button is-light navbar-item" %>
              <% end %>
            </div>
          </div>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/leodi_dashboard_web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "LeoDi" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section>
        <nav role="navigation" class="navbar" aria-label="main navigation">
          <div class="navbar-brand">
            <%= link to: Routes.recipe_path(@conn, :index), class: "navbar-item" do %>
              <div class="brand-wrapper">
                <img src="<%= Routes.static_path(@conn, "/images/motto.png") %>" alt="Motto" />
              </div>
            <% end %>
            <a class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar-menu">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
        </nav>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>