lib/leodi_dashboard_web/router.ex
defmodule LeodiDashboardWeb.Router do
  use LeodiDashboardWeb, :router
  use Pow.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowPersistentSession]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session do
    plug :put_root_layout, {LeodiDashboardWeb.LayoutView, "session.html"}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  scope "/" do
    pipe_through :browser
    pipe_through :session

    pow_session_routes()
    pow_extension_routes()
  end

  scope "/", LeodiDashboardWeb do
    pipe_through [:browser, :protected]

    get "/", PageController, :index

    get "/recipes", RecipeController, :index
    # get "/recipes/new", RecipeController, :new
    live "/recipes/new", RecipeLive.New, :new
    get "/recipes/:id", RecipeController, :show
    delete "/recipes/:id", RecipeController, :delete

    live "/recipes/:id/edit", RecipeLive.Edit, :edit

    get "/recipe_lists", RecipeListController, :index
    live "/recipe_lists/new", RecipeListLive.New, :new
    live "/recipe_lists/:id/edit", RecipeListLive.Edit, :edit
    get "/recipe_lists/:id", RecipeListController, :show
    delete "/recipe_list/:id", RecipeListController, :delete

    resources "/ingredients", IngredientController
    resources "/recipe-ingredients", RecipeIngredientController, only: [:delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", LeodiDashboardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LeodiDashboardWeb.Telemetry
    end
  end
end

lib/leodi_dashboard_web/templates/page/index.html.eex
<div class="container p-4">
  <div class="columns p-4">
    <div class="column">
      <div class="block">
        <h1 class="title">RecipeLists</h1>
        <%= link "New List", to: Routes.recipe_list_new_path(@conn, :new), class: "button is-link level-item" %>
      </div>

      <div class="tile is-ancestor">
        <div class="tile is-vertical">
          <div class="tile">
            <div class="tile is-parent is-vertical">
              <div class="tile is-child">
                <%= for recipe_list <- @recipe_lists do %>
                  <a href="<%= Routes.recipe_list_path(@conn, :show, recipe_list) %>" class="tile notification is-warning">
                    <h2 class="subtitle">
                      <%= recipe_list.name %>
                    </h2>
                  </a>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="block">
      <h1 class="title">Recipes</h1>
      <%= link "New Recipe", to: Routes.recipe_new_path(@conn, :new), class: "button is-link level-item" %>
      </div>

      <div class="tile is-ancestor">
        <div class="tile is-vertical">
          <div class="tile">
            <div class="tile is-parent is-vertical">
              <div class="tile is-child">
                <%= for recipe <- @recipes do %>
                  <a href="<%= Routes.recipe_path(@conn, :show, recipe) %>" class="tile notification is-danger">
                    <h2 class="subtitle">
                      <%= recipe.name %>
                    </h2>
                  </a>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>